name = "RunLengthCodec"
uuid = "8b40ad3e-9b7e-4aaa-99cf-1be18ab7eacc"
authors = ["Gustavo Goretkin <gustavo.goretkin@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[compat]
julia = "1.4"
